name: Publish Docker Image to GitHub Packages

on:
  release:
    types: [published]

env:
  IMAGE_NAME: alterix

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build and Tag Docker Image
        run: |
          docker build -t docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }} ./docker
          docker tag docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }} docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker Image to GitHub Packages
        run: |
          docker push docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}
          docker push docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest